// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.genmymodel.petshop.domain;

import com.genmymodel.petshop.domain.MyClass;

privileged aspect MyClass_Roo_JavaBean {
    
    public String MyClass.getAttribute_() {
        return this.attribute_;
    }
    
    public void MyClass.setAttribute_(String attribute_) {
        this.attribute_ = attribute_;
    }
    
}
